language: node_js
sudo: false
node_js:
  - 8
  - 9
  - 10
  - node

cache: npm

before_script: npm i -g npm@latest
install: npm ci
script: npm run compile

deploy:
  provider: npm
  skip-cleanup: true
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
    node: node

