language: node_js
sudo: false
node_js:
  - 8
  - 9
  - 10
  - node

script:
  - npm run compile

cache: npm

deploy:
  provider: npm
  skip-cleanup: true
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
    node: node

